// AUTO-GENERATED by tools/gen_bible_data.py - do not edit by hand.
// Source: bible.db  |  Malayalam audio Bible (POC)
//
// Durations are read from each MP3 at play time (see app_player), so no per-chapter
// duration table is baked here. The BIBLE_BOOKS table is defined once in bible_data.c
// and shared through this extern declaration, so it is not duplicated in flash across
// the translation units that use it.
#pragma once
#include <stdint.h>

#define BIBLE_BOOK_COUNT     73

typedef enum { BIBLE_OLD = 0, BIBLE_NEW = 1 } bible_testament_t;

typedef struct {
    uint8_t  id;             // 1..73, matches BB in BB_CC.mp3
    uint8_t  chapter_count;  // number of chapters / audio files
    uint8_t  testament;      // bible_testament_t
    const char *name;        // English book name (UI)
} bible_book_t;

extern const bible_book_t BIBLE_BOOKS[BIBLE_BOOK_COUNT];
