#!/usr/bin/env python3
"""Generate a compact, baked-in C header of Bible book/chapter metadata.

Reads bible.db (the 29 MB mobile-app DB) and emits main/bible_data.h containing
only what the audio player needs at runtime:
  - 73 books: id, English name, testament, chapter count
  - 1339 chapter audio durations (ms) in a flat array, indexed per book

Audio files themselves live on the SD card as BB_CC.mp3 (e.g. 01_01.mp3).
Run from the project root:  python3 tools/gen_bible_data.py
"""
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
DB = os.path.normpath(os.path.join(PROJECT, "..", "bible.db"))
OUT = os.path.join(PROJECT, "main", "bible_data.h")


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    con = sqlite3.connect(DB)
    cur = con.cursor()

    books = cur.execute(
        "SELECT _id, chapter_count, book_cat, book_eng_name "
        "FROM books ORDER BY _id"
    ).fetchall()

    # flat duration table, indexed by (book.chapter_offset + chapter_no-1)
    durations = []          # ms per chapter, in book/chapter order
    offsets = {}            # book_id -> first index into durations
    for book_id, chapter_count, _cat, _name in books:
        offsets[book_id] = len(durations)
        rows = cur.execute(
            "SELECT chapter_no, audio_duration FROM book_chapter_dtls "
            "WHERE book_id=? ORDER BY chapter_no",
            (book_id,),
        ).fetchall()
        by_ch = {ch: (dur or 0) for ch, dur in rows}
        for ch in range(1, chapter_count + 1):
            durations.append(int(by_ch.get(ch, 0)))

    con.close()

    lines = []
    w = lines.append
    w("// AUTO-GENERATED by tools/gen_bible_data.py - do not edit by hand.")
    w("// Source: bible.db  |  Malayalam audio Bible (POC)")
    w("#pragma once")
    w("#include <stdint.h>")
    w("")
    w(f"#define BIBLE_BOOK_COUNT     {len(books)}")
    w(f"#define BIBLE_CHAPTER_COUNT  {len(durations)}")
    w("")
    w("typedef enum { BIBLE_OLD = 0, BIBLE_NEW = 1 } bible_testament_t;")
    w("")
    w("typedef struct {")
    w("    uint8_t  id;             // 1..73, matches BB in BB_CC.mp3")
    w("    uint8_t  chapter_count;  // number of chapters / audio files")
    w("    uint8_t  testament;      // bible_testament_t")
    w("    uint16_t chapter_offset; // index into BIBLE_CHAPTER_MS")
    w("    const char *name;        // English book name (UI)")
    w("} bible_book_t;")
    w("")
    w("static const bible_book_t BIBLE_BOOKS[BIBLE_BOOK_COUNT] = {")
    for book_id, chapter_count, cat, name in books:
        tt = "BIBLE_NEW" if cat == "NEW" else "BIBLE_OLD"
        w(f'    {{ {book_id:>2}, {chapter_count:>3}, {tt}, '
          f'{offsets[book_id]:>4}, "{c_escape(name)}" }},')
    w("};")
    w("")
    w("// Per-chapter audio duration in milliseconds (0 = unknown).")
    w("static const uint32_t BIBLE_CHAPTER_MS[BIBLE_CHAPTER_COUNT] = {")
    for i in range(0, len(durations), 12):
        chunk = ", ".join(f"{d:>7}" for d in durations[i:i + 12])
        w(f"    {chunk},")
    w("};")
    w("")
    w("// Duration (ms) of a 1-based chapter in the given book index (0..72).")
    w("static inline uint32_t bible_chapter_ms(int book_idx, int chapter) {")
    w("    const bible_book_t *b = &BIBLE_BOOKS[book_idx];")
    w("    if (chapter < 1 || chapter > b->chapter_count) return 0;")
    w("    return BIBLE_CHAPTER_MS[b->chapter_offset + (chapter - 1)];")
    w("}")
    w("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    total_ms = sum(durations)
    print(f"Wrote {OUT}")
    print(f"  books={len(books)}  chapters={len(durations)}  "
          f"total_audio={total_ms/3600000:.1f} h")


if __name__ == "__main__":
    main()
