#!/usr/bin/env python3
"""Generate the baked-in C table of Bible book metadata.

Reads bible.db (the mobile-app DB) and emits the `bible_data` component:
  - components/bible_data/include/bible_data.h  (types + extern declaration)
  - components/bible_data/bible_data.c          (the 73-book table)

Only id, English name, testament, and chapter count are baked in. Per-chapter audio
durations are computed from each MP3 at play time (see app_player), so they are correct
for every version and are NOT stored here. Audio files live on the SD card as BB_CC.mp3.

Run from the project root:  python3 tools/gen_bible_data.py
"""
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
DB = os.path.normpath(os.path.join(PROJECT, "..", "bible.db"))
COMPONENT = os.path.join(PROJECT, "components", "bible_data")
OUT_H = os.path.join(COMPONENT, "include", "bible_data.h")
OUT_C = os.path.join(COMPONENT, "bible_data.c")

BANNER = ("// AUTO-GENERATED by tools/gen_bible_data.py - do not edit by hand.\n"
          "// Source: bible.db  |  Malayalam audio Bible (POC)")


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    # Open the DB read-only: a plain sqlite3.connect(path) silently CREATES an empty
    # bible.db when it's missing, then fails later with a cryptic "no such table" and
    # leaves the junk file behind. Fail loudly instead (F-45).
    if not os.path.exists(DB):
        raise SystemExit(f"error: {DB} not found — bible.db must sit one level above the project root")
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    cur = con.cursor()

    books = cur.execute(
        "SELECT _id, chapter_count, book_cat, book_eng_name "
        "FROM books ORDER BY _id"
    ).fetchall()
    con.close()

    h = [BANNER, "//",
         "// Durations are read from each MP3 at play time (see app_player), so no per-chapter",
         "// duration table is baked here. The BIBLE_BOOKS table is defined once in bible_data.c",
         "// and shared through this extern declaration, so it is not duplicated in flash across",
         "// the translation units that use it.",
         "#pragma once",
         "#include <stdint.h>",
         "",
         f"#define BIBLE_BOOK_COUNT     {len(books)}",
         "",
         "typedef enum { BIBLE_OLD = 0, BIBLE_NEW = 1 } bible_testament_t;",
         "",
         "typedef struct {",
         "    uint8_t  id;             // 1..73, matches BB in BB_CC.mp3",
         "    uint8_t  chapter_count;  // number of chapters / audio files",
         "    uint8_t  testament;      // bible_testament_t",
         "    const char *name;        // English book name (UI)",
         "} bible_book_t;",
         "",
         "extern const bible_book_t BIBLE_BOOKS[BIBLE_BOOK_COUNT];",
         ""]

    c = [BANNER,
         '#include "bible_data.h"',
         "",
         "const bible_book_t BIBLE_BOOKS[BIBLE_BOOK_COUNT] = {"]
    for book_id, chapter_count, cat, name in books:
        tt = "BIBLE_NEW" if cat == "NEW" else "BIBLE_OLD"
        c.append(f'    {{ {book_id:>2}, {chapter_count:>3}, {tt}, "{c_escape(name)}" }},')
    c.append("};")
    c.append("")

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(h))
    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("\n".join(c))

    print(f"Wrote {OUT_H}")
    print(f"Wrote {OUT_C}")
    print(f"  books={len(books)}")


if __name__ == "__main__":
    main()
