#!/usr/bin/env python3
"""Generate main/biy_data.h from the official Bible-in-a-Year reading plan PDF.

The episode TITLES live in the (readable) SD filenames and are read at runtime,
so this header only bakes what isn't on the card:
  - BIY_PERIODS[12]  : the 12 Great-Adventure-Timeline periods + their day ranges
  - BIY_READING[365] : each day's scripture readings (first / second / psalm)

Source: Ascension's official Bible in a Year reading plan PDF. It is not
included in this repository; download it from Ascension (ascensionpress.com)
and save it as audio_bible/tools/biy_reading_plan.pdf. The generated
main/biy_data.h is committed, so this step is only needed to regenerate it.
Parsing: `pdftotext -layout` keeps the 4 columns space-aligned; day rows are
split on runs of 2+ spaces, periods are the labelled blocks between blank lines.
Run from audio_bible/:  python3 tools/gen_biy_data.py  (requires poppler's pdftotext)
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
PDF = os.path.join(HERE, "biy_reading_plan.pdf")
OUT = os.path.join(PROJECT, "main", "biy_data.h")

# The 12 Great-Adventure-Timeline periods and their (published, fixed) day ranges.
# Period labels are centred over multi-page colour blocks in the PDF, so their day
# spans can't be derived reliably from text position; the ranges below are the
# official ones and are validated below against the parsed readings (boundary book
# changes) + the set of period labels actually found in the PDF.
# (name, first_day, last_day, color) — colours are the Great-Adventure Timeline
# block fills sampled straight from the PDF (tools: pdftoppm + bbox). Divided
# Kingdom is black (#221f20) in print; lifted to a visible grey for the dark UI.
PERIOD_RANGES = [
    ("Early World", 1, 5, 0x64B6BD), ("Patriarchs", 6, 26, 0x771051),
    ("Egypt and Exodus", 27, 51, 0xCD3D37), ("Desert Wanderings", 52, 80, 0xDBBE7D),
    ("Conquest and Judges", 81, 95, 0x31A153), ("Royal Kingdom", 96, 153, 0x493390),
    ("Divided Kingdom", 154, 190, 0x9A9A9A), ("Exile", 191, 241, 0x8DB5E2),
    ("Return", 242, 280, 0xF4D02B), ("Maccabean Revolt", 281, 312, 0xD8792D),
    ("Messianic Fulfillment", 313, 358, 0xB1922F), ("The Church", 359, 365, 0xEFEFEF),
]
PERIOD_NAMES = [p[0] for p in PERIOD_RANGES]
DAY_RE = re.compile(r"^Day\s+(\d+)\b")


def layout_text():
    out = subprocess.run(["pdftotext", "-layout", PDF, "-"],
                         capture_output=True, text=True, check=True)
    return out.stdout


def parse_day_row(line):
    """'Day 6   Genesis 12-13   Job 1-2   Proverbs 1:1-7' -> (6, first, second, psalm)."""
    parts = re.split(r"\s{2,}", line.strip())
    day = int(re.match(r"Day\s+(\d+)", parts[0]).group(1))
    cols = parts[1:]
    if len(cols) >= 3:
        first, second, psalm = cols[0], cols[1], cols[2]
    elif len(cols) == 2:
        first, second, psalm = cols[0], "", cols[1]   # no second reading that day
    else:
        first, second, psalm = cols[0], "", ""
    return day, first.strip(), second.strip(), psalm.strip()


def parse(text):
    """Return (readings {day: (first,second,psalm)}, labels_found set)."""
    readings, labels = {}, set()
    for raw in text.replace("\f", "\n").splitlines():
        s = raw.strip()
        if not s:
            continue
        if DAY_RE.match(s):
            day, first, second, psalm = parse_day_row(s)
            readings[day] = (first, second, psalm)
        elif s in PERIOD_NAMES:
            labels.add(s)
    return readings, labels


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(readings, labels, periods):
    days = sorted(readings)
    assert days == list(range(1, 366)), f"expected days 1..365, got {len(days)}"
    for d in days:
        assert readings[d][0] and readings[d][2], f"day {d} missing first/psalm: {readings[d]}"
    # the PDF must contain all 12 period labels (confirms the right document/parse)
    assert labels == set(PERIOD_NAMES), f"period labels mismatch: {set(PERIOD_NAMES) ^ labels}"
    # ranges must tile 1..365 contiguously
    expect = 1
    for name, f, l, color in periods:
        assert f == expect, f"period '{name}' starts at {f}, expected {expect}"
        expect = l + 1
    assert expect == 366, f"periods end at {expect-1}, expected 365"

    lines = [
        "// AUTO-GENERATED by tools/gen_biy_data.py - do not edit by hand.",
        "// Source: tools/biy_reading_plan.pdf  |  Bible in a Year (Fr. Mike Schmitz / Ascension)",
        "// Episode titles are read from the SD filenames at runtime; only readings are baked here.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define BIY_DAY_COUNT   365",
        "#define BIY_PERIOD_COUNT 12",
        "",
        "typedef struct { const char *name; uint16_t first_day, last_day; uint32_t color; } biy_period_t;",
        "typedef struct { const char *first, *second, *psalm; } biy_reading_t;",
        "",
        f"static const biy_period_t BIY_PERIODS[BIY_PERIOD_COUNT] = {{",
    ]
    for name, f, l, color in periods:
        lines.append(f'    {{ "{esc(name)}", {f}, {l}, 0x{color:06X} }},')
    lines.append("};")
    lines.append("")
    lines.append("// Indexed by (day - 1), day = 1..365.")
    lines.append("static const biy_reading_t BIY_READING[BIY_DAY_COUNT] = {")
    for d in days:
        first, second, psalm = readings[d]
        lines.append(f'    {{ "{esc(first)}", "{esc(second)}", "{esc(psalm)}" }},  // Day {d}')
    lines.append("};")
    lines.append("")
    lines.append("// Period (0..11) containing a 1-based day, or -1 if out of range.")
    lines.append("static inline int biy_period_of(int day) {")
    lines.append("    for (int i = 0; i < BIY_PERIOD_COUNT; i++)")
    lines.append("        if (day >= BIY_PERIODS[i].first_day && day <= BIY_PERIODS[i].last_day) return i;")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")
    lines.append("// Readings for a 1-based day, or NULL if out of range.")
    lines.append("static inline const biy_reading_t *biy_reading(int day) {")
    lines.append("    if (day < 1 || day > BIY_DAY_COUNT) return 0;")
    lines.append("    return &BIY_READING[day - 1];")
    lines.append("}")
    lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")
    for name, fd, ld, color in periods:
        print(f"  {name:22s} Day {fd}-{ld}  #{color:06X}")


def main():
    if not os.path.exists(PDF):
        sys.exit(f"missing {PDF}")
    readings, labels = parse(layout_text())
    emit(readings, labels, PERIOD_RANGES)


if __name__ == "__main__":
    main()
