// AUTO-GENERATED by tools/gen_bible_data.py - do not edit by hand.
// Source: bible.db  |  Malayalam audio Bible (POC)
// NOTE: the baked per-chapter duration table was removed — durations are now read
// from each MP3 at play time (see app_player), so they're correct for every version.
#pragma once
#include <stdint.h>

#define BIBLE_BOOK_COUNT     73

typedef enum { BIBLE_OLD = 0, BIBLE_NEW = 1 } bible_testament_t;

typedef struct {
    uint8_t  id;             // 1..73, matches BB in BB_CC.mp3
    uint8_t  chapter_count;  // number of chapters / audio files
    uint8_t  testament;      // bible_testament_t
    uint16_t chapter_offset; // (unused since durations moved to runtime)
    const char *name;        // English book name (UI)
} bible_book_t;

static const bible_book_t BIBLE_BOOKS[BIBLE_BOOK_COUNT] = {
    {  1,  50, BIBLE_OLD,    0, "Genesis" },
    {  2,  40, BIBLE_OLD,   50, "Exodus" },
    {  3,  27, BIBLE_OLD,   90, "Leviticus" },
    {  4,  36, BIBLE_OLD,  117, "Numbers" },
    {  5,  34, BIBLE_OLD,  153, "Deuteronomy" },
    {  6,  24, BIBLE_OLD,  187, "Joshua" },
    {  7,  21, BIBLE_OLD,  211, "Judges" },
    {  8,   4, BIBLE_OLD,  232, "Ruth" },
    {  9,  31, BIBLE_OLD,  236, "1 Samuel" },
    { 10,  24, BIBLE_OLD,  267, "2 Samuel" },
    { 11,  22, BIBLE_OLD,  291, "1 Kings" },
    { 12,  25, BIBLE_OLD,  313, "2 Kings" },
    { 13,  29, BIBLE_OLD,  338, "1 Chronicles" },
    { 14,  36, BIBLE_OLD,  367, "2 Chronicles" },
    { 15,  10, BIBLE_OLD,  403, "Ezra" },
    { 16,  13, BIBLE_OLD,  413, "Nehemiah" },
    { 17,  14, BIBLE_OLD,  426, "Tobit" },
    { 18,  16, BIBLE_OLD,  440, "Judith" },
    { 19,  21, BIBLE_OLD,  456, "Esther" },
    { 20,  16, BIBLE_OLD,  477, "1 Maccabees" },
    { 21,  15, BIBLE_OLD,  493, "2 Maccabees" },
    { 22,  42, BIBLE_OLD,  508, "Job" },
    { 23, 150, BIBLE_OLD,  550, "Psalms" },
    { 24,  31, BIBLE_OLD,  700, "The Proverbs" },
    { 25,  12, BIBLE_OLD,  731, "Ecclesiastes" },
    { 26,   8, BIBLE_OLD,  743, "The Song of Songs" },
    { 27,  19, BIBLE_OLD,  751, "Wisdom" },
    { 28,  51, BIBLE_OLD,  770, "Ecclesiasticus" },
    { 29,  66, BIBLE_OLD,  821, "Isaiah" },
    { 30,  52, BIBLE_OLD,  887, "Jeremiah" },
    { 31,   5, BIBLE_OLD,  939, "Lamentations" },
    { 32,   6, BIBLE_OLD,  944, "Baruch" },
    { 33,  48, BIBLE_OLD,  950, "Ezekiel" },
    { 34,  14, BIBLE_OLD,  998, "Daniel" },
    { 35,  14, BIBLE_OLD, 1012, "Hosea" },
    { 36,   3, BIBLE_OLD, 1026, "Joel" },
    { 37,   9, BIBLE_OLD, 1029, "Amos" },
    { 38,   1, BIBLE_OLD, 1038, "Obadiah" },
    { 39,   4, BIBLE_OLD, 1039, "Jonah" },
    { 40,   7, BIBLE_OLD, 1043, "Micah" },
    { 41,   3, BIBLE_OLD, 1050, "Nahum" },
    { 42,   3, BIBLE_OLD, 1053, "Habakkuk" },
    { 43,   3, BIBLE_OLD, 1056, "Zephaniah" },
    { 44,   2, BIBLE_OLD, 1059, "Haggai" },
    { 45,  14, BIBLE_OLD, 1061, "Zechariah" },
    { 46,   4, BIBLE_OLD, 1075, "Malachi" },
    { 47,  28, BIBLE_NEW, 1079, "Matthew" },
    { 48,  16, BIBLE_NEW, 1107, "Mark" },
    { 49,  24, BIBLE_NEW, 1123, "Luke" },
    { 50,  21, BIBLE_NEW, 1147, "John" },
    { 51,  28, BIBLE_NEW, 1168, "Acts of Apostles" },
    { 52,  16, BIBLE_NEW, 1196, "Romans" },
    { 53,  16, BIBLE_NEW, 1212, "1 Corinthians" },
    { 54,  13, BIBLE_NEW, 1228, "2 Corinthians" },
    { 55,   6, BIBLE_NEW, 1241, "Galatians" },
    { 56,   6, BIBLE_NEW, 1247, "Ephesians" },
    { 57,   4, BIBLE_NEW, 1253, "Philippians" },
    { 58,   4, BIBLE_NEW, 1257, "Colossians" },
    { 59,   5, BIBLE_NEW, 1261, "1 Thessalonians" },
    { 60,   3, BIBLE_NEW, 1266, "2 Thessalonians" },
    { 61,   6, BIBLE_NEW, 1269, "1 Timothy" },
    { 62,   4, BIBLE_NEW, 1275, "2 Timothy" },
    { 63,   3, BIBLE_NEW, 1279, "Titus" },
    { 64,   1, BIBLE_NEW, 1282, "Philemon" },
    { 65,  13, BIBLE_NEW, 1283, "Hebrews" },
    { 66,   5, BIBLE_NEW, 1296, "James" },
    { 67,   5, BIBLE_NEW, 1301, "1 Peter" },
    { 68,   3, BIBLE_NEW, 1306, "2 Peter" },
    { 69,   5, BIBLE_NEW, 1309, "1 John" },
    { 70,   1, BIBLE_NEW, 1314, "2 John" },
    { 71,   1, BIBLE_NEW, 1315, "3 John" },
    { 72,   1, BIBLE_NEW, 1316, "Jude" },
    { 73,  22, BIBLE_NEW, 1317, "Revelation" },
};

